# src/mysed/Makefile
CC = gcc
CFLAGS = -Wall -I../../include

# 库名称
LIBNAME := mysed
# 静态库输出名：libmysed.a
LIB := lib$(LIBNAME).a
# 最终库输出目录（比如 ./obj/src/mysed/）
OBJDIR ?= ./obj/mysed
# 最终 .a 文件路径
LIB_PATH := $(OBJDIR)/$(LIB)

# 源文件
SRCS := mysed.c
OBJS := $(SRCS:.c=.o)
OBJS := $(patsubst %.o,$(OBJDIR)/%.o,$(OBJS))

all: $(LIB_PATH)

# 生成 .o 文件规则
$(OBJDIR)/%.o: %.c
	mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -c $< -o $@

# 打包静态库
$(LIB_PATH): $(OBJS)
	ar rcs $(LIB_PATH) $(OBJS)

clean:
	rm -rf $(OBJDIR)/*.o $(LIB_PATH)
